### ISSUE TITLE
Loading State (FE)

### ISSUE THREAD

**Issue by KevinFrederick** [Rionase/FE_Terbangin#2]

**Comment by KevinFrederick** [comment]
Link Merge Request : [https://github.com/Rionase/FE_Terbangin/pull/5](url)
Link Branch : [https://github.com/Rionase/FE_Terbangin/tree/Kevin-Loading_State(FE)](url)
Commit : [c7281d39b527dc5c7bde4c92d8abaa4a12d32444](url)

**Comment by Resolt123** [comment]
Membuat sebuah tampilan animasi ketika terjadi loading pada web app.

Before:
![Image](https://github.com/user-attachments/assets/5e9bc5cd-c664-4d73-8ee6-d5f076006e90)

After:
![Image](https://github.com/user-attachments/assets/f71e1729-161e-410c-a3f7-be71ef952888)
