### ISSUE TITLE
Fix Bug Pencarian Tiket (FE)

### ISSUE THREAD

**Issue by KevinFrederick** [Rionase/FE_Terbangin#3]

**Comment by KevinFrederick** [comment]
Link Merge Request : [https://github.com/Rionase/FE_Terbangin/pull/4](url)
Link Branch : [https://github.com/Rionase/FE_Terbangin/tree/Kevin-Fix_Bug_Pencarian_Tiket(FE)](url)
Commit :  8c374b056fb2935185bc9615e81b3c2943859964

**Comment by Resolt123** [comment]
Memperbaiki sebuah bug anomali yang terjadi pada saat ingin melakukan pencarian tiket pesawat dimana data tiket yang diberikan tidak sesuai dengan untuk tanggalnya.

lokasi page:
![Image](https://github.com/user-attachments/assets/162af977-3b50-4ac4-9fa2-1551d9b00302)
