### ISSUE TITLE
Recommendation (FE)

### ISSUE THREAD

**Issue by Rionase** [Rionase/FE_Terbangin#6]

**Comment by Rionase** [comment]
Link Merge Request : https://github.com/Rionase/FE_Terbangin/pull/7
Link Branch : https://github.com/Rionase/FE_Terbangin/tree/Nicholas-Recomendation(FE)
Commit : 02891d291154835e2f5d5119090d4e4cdf3c7ef5

**Comment by Resolt123** [comment]
Membuat tampilan dari tiket tiket yang direkomendasikan berdasarkan harga dan benua di halaman homesite.

Before:
![Image](https://github.com/user-attachments/assets/4e3fbc56-8377-4ada-a241-4ba238f34cf2)

After:
![Image](https://github.com/user-attachments/assets/01a9c14a-fa6d-4558-9c1f-4c7f894960d7)
